"""add aluno numero chamada

Revision ID: 1e03c191331b
Revises: e7af6fd55244
Create Date: 2026-02-10 13:26:52.888161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e03c191331b'
down_revision = 'e7af6fd55244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_chamada', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_column('numero_chamada')

    # ### end Alembic commands ###
