"""Adiciona modelo DiarioAnotacao

Revision ID: 22089e9fc927
Revises: 2c3b5e6f7a8b
Create Date: 2026-02-14 12:56:23.273863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22089e9fc927'
down_revision = '2c3b5e6f7a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diario_anotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('anotacao', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diario_anotacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diario_anotacao_professor_id'), ['professor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diario_anotacao_turma_id'), ['turma_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diario_anotacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diario_anotacao_turma_id'))
        batch_op.drop_index(batch_op.f('ix_diario_anotacao_professor_id'))

    op.drop_table('diario_anotacao')
    # ### end Alembic commands ###
