"""add turma horarios

Revision ID: 2f5111cc730b
Revises: d51d4adf5df4
Create Date: 2026-02-10 14:28:29.958438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5111cc730b'
down_revision = 'd51d4adf5df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turma_horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turma_id', 'dia_semana', 'hora', name='uq_turma_horario_dia_hora')
    )
    with op.batch_alter_table('turma_horario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turma_horario_turma_id'), ['turma_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma_horario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turma_horario_turma_id'))

    op.drop_table('turma_horario')
    # ### end Alembic commands ###
