"""init

Revision ID: 59bfa6d14d58
Revises: 
Create Date: 2026-02-10 12:52:56.288939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bfa6d14d58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('escola', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professor_email'), ['email'], unique=True)

    op.create_table('turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('disciplina', sa.String(length=120), nullable=True),
    sa.Column('ano_serie', sa.String(length=120), nullable=True),
    sa.Column('trimestre_atual', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turma_professor_id'), ['professor_id'], unique=False)

    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('matricula', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aluno_turma_id'), ['turma_id'], unique=False)

    op.create_table('atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('trimestre', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('nota_maxima', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('atividade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atividade_turma_id'), ['turma_id'], unique=False)

    op.create_table('avaliacao_aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('comentario_curto', sa.String(length=255), nullable=True),
    sa.Column('comentario_longo', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atividade_id', 'aluno_id', name='uq_avaliacao_atividade_aluno')
    )
    with op.batch_alter_table('avaliacao_aluno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacao_aluno_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacao_aluno_atividade_id'), ['atividade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avaliacao_aluno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacao_aluno_atividade_id'))
        batch_op.drop_index(batch_op.f('ix_avaliacao_aluno_aluno_id'))

    op.drop_table('avaliacao_aluno')
    with op.batch_alter_table('atividade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atividade_turma_id'))

    op.drop_table('atividade')
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aluno_turma_id'))

    op.drop_table('aluno')
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turma_professor_id'))

    op.drop_table('turma')
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professor_email'))

    op.drop_table('professor')
    # ### end Alembic commands ###
