"""Adiciona campo titulo em DiarioAnotacao

Revision ID: 68b63e003575
Revises: 22089e9fc927
Create Date: 2026-02-14 13:08:56.021223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b63e003575'
down_revision = '22089e9fc927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diario_anotacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diario_anotacao', schema=None) as batch_op:
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
