"""add atividade aulas e lancamentos

Revision ID: d51d4adf5df4
Revises: 1e03c191331b
Create Date: 2026-02-10 13:45:43.675720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51d4adf5df4'
down_revision = '1e03c191331b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividade_aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atividade_id', 'numero', name='uq_atividade_aula_numero')
    )
    with op.batch_alter_table('atividade_aula', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atividade_aula_atividade_id'), ['atividade_id'], unique=False)

    op.create_table('lancamento_aula_aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['aula_id'], ['atividade_aula.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aula_id', 'aluno_id', name='uq_lancamento_aula_aluno')
    )
    with op.batch_alter_table('lancamento_aula_aluno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamento_aula_aluno_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_aula_aluno_aula_id'), ['aula_id'], unique=False)

    with op.batch_alter_table('atividade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aulas_planejadas', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividade', schema=None) as batch_op:
        batch_op.drop_column('aulas_planejadas')

    with op.batch_alter_table('lancamento_aula_aluno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamento_aula_aluno_aula_id'))
        batch_op.drop_index(batch_op.f('ix_lancamento_aula_aluno_aluno_id'))

    op.drop_table('lancamento_aula_aluno')
    with op.batch_alter_table('atividade_aula', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atividade_aula_atividade_id'))

    op.drop_table('atividade_aula')
    # ### end Alembic commands ###
