"""add turma fields

Revision ID: e7af6fd55244
Revises: 59bfa6d14d58
Create Date: 2026-02-10 13:18:42.293607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7af6fd55244'
down_revision = '59bfa6d14d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serie', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('turma_letra', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('periodo', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('ano_letivo', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.drop_column('ano_letivo')
        batch_op.drop_column('periodo')
        batch_op.drop_column('turma_letra')
        batch_op.drop_column('serie')

    # ### end Alembic commands ###
